version: "3.7"
services:
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'database'
      MYSQL_PASSWORD: 'database'
      MYSQL_ROOT_PASSWORD: 'database'
    ports:
      - '3307:3307'
    expose:
      - '3307'
    volumes:
      - my-db:/var/lib/mysql
      
  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
    - "8081:8081"
    volumes:
      - .:/app
  pma:
      depends_on:
       - database
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
       - '8009:8009'
      environment:
        PMA_HOST: database

volumes:
  my-db:
