// @/main.go
package main

import (
	"back/config"
	"back/handlers"
	"log"

	_ "back/docs" // docs is generated by Swag CLI, you have to import it.

	"github.com/gofiber/fiber/v2"
	fiberSwagger "github.com/swaggo/fiber-swagger"
)

// @title Cafe; API
// @version 1.0
// @description This is a documentations for Cafe; API.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8080
// @BasePath /

func main() {
	app := fiber.New()
	config.Connect()

	app.Get("/swagger/*", fiberSwagger.WrapHandler)

	app.Get("/users", handlers.GetUsers)
	app.Get("/user/:id", handlers.GetUser)
	app.Post("/users", handlers.AddUser)
	app.Put("/users/:id", handlers.UpdateUser)
	app.Delete("/users/:id", handlers.RemoveUser)

	app.Get("/posts", handlers.GetPosts)
	app.Get("/post/:id", handlers.GetPost)
	app.Post("/posts", handlers.AddPost)
	app.Put("/posts/:id", handlers.UpdatePost)
	app.Delete("/posts/:id", handlers.RemovePost)

	log.Fatal(app.Listen(":8080"))
}
